language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  
before_script:
#  - psql -c 'create database my_zipcode_gem_test;' -U postgres
#  - mysql -e 'create database my_zipcode_gem_test;'
  
gemfile:
  - rails3_2.gemfile
  - rails4_0.gemfile
  - rails4_1.gemfile
  
branches:
  only:
    - master
